overhaul the god.init, now supports terminate action when run as a KILL script.

diff --git a/lib/cap_recipes/tasks/god/god.init b/lib/cap_recipes/tasks/god/god.init
--- a/lib/cap_recipes/tasks/god/god.init
+++ b/lib/cap_recipes/tasks/god/god.init
@@ -1,66 +1,157 @@
-#!/bin/sh
-
+#! /bin/sh
 ### BEGIN INIT INFO
-# Provides:             god
-# Required-Start:       $all
-# Required-Stop:        $all
-# Default-Start:        2 3 4 5
-# Default-Stop:         0 1 6
-# Short-Description:    God
+# Provides:          god
+# Required-Start:    $remote_fs $syslog
+# Required-Stop:     $remote_fs $syslog
+# Default-Start:     2 3 4 5
+# Default-Stop:      0 1 6
+# Short-Description: God initscript
 ### END INIT INFO
 
-NAME=god
-DESC=god
-DAEMON=<%=god_daemon%>
-GOD_CONFIG=<%=god_config%>
+# Author: Johnny Domino (domino@cmu.edu)
+# Adapted: Donovan Bray (donnoman@donovanbray.com)
+
+# PATH should only include /usr/* if it runs after the mountnfs.sh script
 PATH="<%="#{base_ruby_path}/bin"%>:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
-LOG=<%=god_log_path%>
-PID=<%=god_pid_path%>
+DESC="God Monitoring Tool"
+NAME=god
+CONF=<%=god_config%>
 LEVEL=<%=god_log_level%>
+LOGFILE="<%=god_log_path%>" ; mkdir -p `dirname $LOGFILE`
+PIDFILE="<%=god_pid_path%>" ; mkdir -p `dirname $PIDFILE`
+DAEMON=<%=god_daemon%>
+DAEMON_ARGS="-c $CONF -P $PIDFILE --log-level $LEVEL <%= god_log_path ? '--log $LOGFILE' : '' %>"
+SCRIPTNAME=<%=god_init%>
+OPEN_SOCKET=<%= god_open_socket ? 'yes' : 'no' %>
+USE_TERMINATE_ON_KILL=<%= god_use_terminate_on_kill ? 'yes' : 'no' %>
 
-set -e
+# Exit if the package is not installed
+[ -x "$DAEMON" ] || exit 0
 
-# Make sure the binary and the config file are present before proceeding
-test -x $DAEMON || exit 0
+# Read configuration variable file if it is present
+[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
+# Load the VERBOSE setting and other rcS variables
+. /lib/init/vars.sh
+
+# Define LSB log_* functions.
+# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
 . /lib/lsb/init-functions
 
-RETVAL=0
+#
+# Function that starts the daemon/service
+#
+do_start()
+{
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
+        || return 1
+    start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+        $DAEMON_ARGS \
+        || return 2
+    # Add code here, if necessary, that waits for the process to be ready
+    # to handle requests from services started subsequently which depend
+    # on this one.  As a last resort, sleep for some time.
+    [ "$OPEN_SOCKET" != no ] && sleep 3 && sh -c "chmod 0777 /tmp/god.*.sock;true"
+}
+
+# kills god + everything god is monitoring
+do_terminate()
+{
+    $DAEMON terminate
+    RETVAL="$?"
+    return "$RETVAL"
+}
+
+#
+# Function that stops the daemon/service
+#
+do_stop()
+{
+    $DAEMON quit
+    RETVAL="$?"
+    return "$RETVAL"
+}
+
+#
+# Function that sends a SIGHUP to the daemon/service
+#
+do_reload() {
+    #
+    # If the daemon can reload its configuration without
+    # restarting (for example, when it is sent a SIGHUP),
+    # then implement that here.
+    #
+    log_daemon_msg "Reloading $DESC" "$NAME"
+    $DAEMON load $CONF
+    return 0
+}
 
 case "$1" in
   start)
-    echo -n "Starting $DESC: "
-    $DAEMON -c $GOD_CONFIG -P $PID --log-level $LEVEL <%= god_log_path ? '--log $LOG' : '' %>
-    RETVAL=$?
-    sleep 2
-    sh -c "chmod 0777 /tmp/god.*.sock;true"
-    echo "$NAME."
+    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    do_start
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
     ;;
   stop)
-    echo -n "Stopping $DESC: "
-    pkill -9 -f $DAEMON
-    RETVAL=$?
-    echo "$NAME."
+    if [ "$0" != "$SCRIPTNAME" ] && [ "$USE_TERMINATE_ON_KILL" = "yes" ]; then
+      [ "$VERBOSE" != no ] && log_daemon_msg "Terminating $DESC" "$NAME"
+      do_terminate
+    else
+      [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+      do_stop
+    fi
+    case "$?" in
+        0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+        2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
     ;;
-  restart)
-    echo -n "Restarting $DESC: "
-    set +e
-    pkill -9 -f $DAEMON
-    set -e
-    $DAEMON -c $GOD_CONFIG -P $PID --log-level $LEVEL <%= god_log_path ? '--log $LOG' : '' %>
-    RETVAL=$?
-    sleep 2
-    sh -c "chmod 0777 /tmp/god.*.sock;true"
-    echo "$NAME."
+  terminate)
+    [ "$VERBOSE" != no ] && log_daemon_msg "Terminating $DESC" "$NAME"
+    do_terminate
+    case "$?" in
+            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
+            2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+    esac
     ;;
   status)
-    $DAEMON status
-    RETVAL=$?
+    $DAEMON status && exit 0 || exit $?
+    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+    ;;
+  reload|force-reload)
+    do_reload
+    log_end_msg $?
+    ;;
+  restart)
+    #
+    # If the "reload" option is implemented then remove the
+    # 'force-reload' alias
+    #
+    log_daemon_msg "Restarting $DESC" "$NAME"
+    do_stop
+    case "$?" in
+      0|1)
+        do_start
+        case "$?" in
+            0) log_end_msg 0 ;;
+            1) log_end_msg 1 ;; # Old process is still running
+            *) log_end_msg 1 ;; # Failed to start
+        esac
+        ;;
+      *)
+        # Failed to stop
+        log_end_msg 1
+        ;;
+    esac
     ;;
   *)
-    echo "Usage: god {start|stop|restart|status}"
-    exit 1
+    echo "Usage: $SCRIPTNAME {start|stop|status|restart|terminate|force-reload}" >&2
+    exit 3
     ;;
 esac
-
-exit $RETVAL
